apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: apic-job-clusterrole
rules:
- apiGroups: ["apiextensions.k8s.io"] 
  resources: ["customresourcedefinitions"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: apic-job-clusterrolebinding
subjects:
- kind: ServiceAccount
  name: default
  namespace: tools
roleRef:
  kind: ClusterRole
  name: apic-job-clusterrole
  apiGroup: rbac.authorization.k8s.io
