apiVersion: appconnect.ibm.com/v1beta1
kind: Configuration
metadata:
  name: ace-cp4i-demo-policy
  namespace: tools
spec:
  type: policyproject
  description: Policy to configure default values for CP4I Demo
  contents: |
    UEsDBAoAAAAAADJUxlQAAAAAAAAAAAAAAAAJABwAQ1A0SURFTU8vVVQJAANQHp5iUB6eYnV4CwAB
    BPUBAAAEFAAAAFBLAwQUAAAACAAyVMZUtD8wqtQAAAACAgAAEQAcAENQNElERU1PLy5wcm9qZWN0
    VVQJAANQHp5iUB6eYnV4CwABBPUBAAAEFAAAAKVRvQrCMBic9Smku4mCg0OsYFVw8AfUB2jTT4k0
    SUlS0bc3fxZ1cNDt7rjcHV/I9Mar3hWUZlJMkiEaJD0QVJZMnCfJ8bDsj5Np2iW1khegZg6aKlYb
    a067HSJyDmm2G63mi/WWYE+tTCXnIExK8BNZMSZoh/ErKRpWlfsaqCWRZfZZLkonxBIbhFjBERgp
    K434yaBaVozeUcOQfwMK7bwyC6ydYyNydW7cDh0ofuMEf3b+NCKg4t/yKMR72F7TKAjWgL+v2HiP
    q/del9dGtGd/+8UHUEsDBBQAAAAIADJUxlRsQrsBsgAAABMBAAAmABwAQ1A0SURFTU8vamdyLWRl
    bW8tcHJvcGVydGllcy5wb2xpY3l4bWxVVAkAA1AenmJQHp5idXgLAAEE9QEAAAQUAAAAXY/NDoIw
    EITvPkXTe0ETDh74MdFovBgP+ABQFrKk2zYtGnl7S5BIPG02883OTlq8SbEXOI9GZ3wXbTkDLU2D
    usv4ozyLPS/yTWqNQong8w1j8zKyeZSjhUB6cCdoUUPDv8KtoiD0nRMNkBHWGQtuCDcWoASyqhr+
    3FNCyACqUInWGcqrhlALaRM8YE2RNJTGK3nN+2fdgxzyiwMYQgXPJoQd78l18SzIVCSeHwn94l/B
    D1BLAwQUAAAACAAyVMZULsMb/JYAAAD4AAAAGgAcAENQNElERU1PL3BvbGljeS5kZXNjcmlwdG9y
    VVQJAANQHp5iUB6eYnV4CwABBPUBAAAEFAAAAI2OQQrCMBBF94J3CLM3UVdSmnYjrl3oAdp0qpEk
    UzKD2NsbEQQ34v6/91/dPmJQd8zsKVnY6DUoTI4Gny4WzqfDageKpUtDFyihhRkZ2ma5qBNvq4mC
    d/Mx0w2d7JFd9pNQVsWZ2MJVZKqMcRS176NGIQqs4yh6+Gx13zHCm6iK80/q6xlKj1J1xhFziUc2
    r0Dzo7B5AlBLAQIeAwoAAAAAADJUxlQAAAAAAAAAAAAAAAAJABgAAAAAAAAAEADtQQAAAABDUDRJ
    REVNTy9VVAUAA1AenmJ1eAsAAQT1AQAABBQAAABQSwECHgMUAAAACAAyVMZUtD8wqtQAAAACAgAA
    EQAYAAAAAAABAAAApIFDAAAAQ1A0SURFTU8vLnByb2plY3RVVAUAA1AenmJ1eAsAAQT1AQAABBQA
    AABQSwECHgMUAAAACAAyVMZUbEK7AbIAAAATAQAAJgAYAAAAAAABAAAApIFiAQAAQ1A0SURFTU8v
    amdyLWRlbW8tcHJvcGVydGllcy5wb2xpY3l4bWxVVAUAA1AenmJ1eAsAAQT1AQAABBQAAABQSwEC
    HgMUAAAACAAyVMZULsMb/JYAAAD4AAAAGgAYAAAAAAABAAAApIF0AgAAQ1A0SURFTU8vcG9saWN5
    LmRlc2NyaXB0b3JVVAUAA1AenmJ1eAsAAQT1AQAABBQAAABQSwUGAAAAAAQABAByAQAAXgMAAAAA