kind: Job
apiVersion: batch/v1
metadata:
  name: es-demo-setup-job
  namespace: tools
  labels:
    job-name: es-demo-setup-job
spec:
  parallelism: 1
  completions: 1
  backoffLimit: 1
  selector: {}
  template:
    metadata:
      name: run
      labels:
        job-name: es-demo-setup-job
    spec:
      containers:
        - name: run
          image: 'quay.io/vbudi/sko-job:1.1'
          command:
            - "/user1/es-initial-config.sh"
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler