apiVersion: appconnect.ibm.com/v1beta1
kind: IntegrationServer
metadata:
  name: jgr-mqapi-prem
  namespace: tools
spec:
  adminServerSecure: true
  createDashboardUsers: true
  designerFlowsOperationMode: disabled
  enableMetrics: true
  license:
    accept: true
    license: L-APEH-C9NCK6
    use: CloudPakForIntegrationNonProduction
  pod:
    containers:
      runtime:
        resources:
          limits:
            cpu: 300m
            memory: 350Mi
          requests:
            cpu: 300m
            memory: 300Mi
  replicas: 1
  router:
    timeout: 120s
  service:
    endpointType: http
  version: '12.0'
  barURL: >-
    https://github.com/gomezrjo/cp4idemo/raw/main/barfiles/jgr-cp4i-mqapi-prem.bar
  configurations:
    - github-barauth
    - ace-qmgr-demo-policy
  tracing:
    enabled: true
    namespace: tools